addition:
  num_samples: 10000
  arg_size: 10
  num_epochs: 150

mnist:
  train:
    num_samples: 20000
    arg_size: 10
  test_small:
    num_samples: 1000
    arg_size: 10
  test_large:
    num_samples: 1000
    arg_size: 100
  num_epochs: 50

batch_size: 32
optimizer: adam()
val_interval: 10

clip_grad_norm: null
clip_grad: null

pretrained:
  blackbox_estimator: null

download: true
device: -1